name: milan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.10.4
  - frozenlist=1.2.0
  - gast=0.3.3
  - giflib=5.2.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jbig=2.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcurl=7.82.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydotplus=2.0.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.27.1
  - scikit-learn=0.24.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cachetools==4.2.4
    - cmdstanpy==1.0.7
    - contourpy==1.0.5
    - convertdate==2.4.0
    - ephem==4.1.3
    - fonttools==4.37.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - hijri-converter==2.2.4
    - holidays==0.16
    - keras==2.4.3
    - korean-lunar-calendar==0.3.1
    - lunarcalendar==0.0.9
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.4.1
    - numpy==1.19.5
    - pandas==1.2.2
    - pillow==9.2.0
    - prophet==1.1.1
    - pymeeus==0.5.11
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.8.0
    - seaborn==0.12.0
    - setuptools-git==1.2
    - statsmodels==0.13.5
    - tensorboard==2.2.2
    - tqdm==4.64.1
    - ujson==5.5.0
    - werkzeug==2.2.2
